### ISSUE TITLE
Cannot get DAG size for pin in cron job

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/nft.storage#206]
There's a few pins that are failing to be updated with their size in the cron job and are "stuck". Either they are _massive_ and 30 minutes is not enough to determine their size or they are not fully pinned (should not be the case). Needs investigation and resolution:

```console
AbortError: following up on QmVq2q1WBMHBBbQR37BKbiw9wkJThYYzHgLucAikyGYsTf: The user aborted a request.
    at abort (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1418:16)
    at EventTarget.abortAndFinalize (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1433:4)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at EventTarget.dispatchEvent (node:internal/event_target:409:26)
    at abortSignal (node:internal/abort_controller:98:10)
    at AbortController.abort (node:internal/abort_controller:123:5)
    at Timeout.<anonymous> (file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/lib/ipfs.js:25:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'aborted'
}
AbortError: following up on Qmdvh1Xa8spstyGroksPx7A7NzUpdYtEJsjy9x4kyTM385: The user aborted a request.
    at abort (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1418:16)
    at EventTarget.abortAndFinalize (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1433:4)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at EventTarget.dispatchEvent (node:internal/event_target:409:26)
    at abortSignal (node:internal/abort_controller:98:10)
    at AbortController.abort (node:internal/abort_controller:123:5)
    at Timeout.<anonymous> (file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/lib/ipfs.js:25:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'aborted'
}
AbortError: following up on QmXpR4Ai49CeUhc2WwfvpMkeTe1jEaZFkLv1YaLdBzaY6J: The user aborted a request.
    at abort (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1418:16)
    at EventTarget.abortAndFinalize (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1433:4)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at EventTarget.dispatchEvent (node:internal/event_target:409:26)
    at abortSignal (node:internal/abort_controller:98:10)
    at AbortController.abort (node:internal/abort_controller:123:5)
    at Timeout.<anonymous> (file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/lib/ipfs.js:25:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'aborted'
}
AbortError: following up on Qmazo7s2m39dZUySaeBHeVr23WhoKJvHh5gnvwbg8xRAw9: The user aborted a request.
    at abort (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1418:16)
    at EventTarget.abortAndFinalize (/home/runner/work/nft.storage/nft.storage/node_modules/node-fetch/lib/index.js:1433:4)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at EventTarget.dispatchEvent (node:internal/event_target:409:26)
    at abortSignal (node:internal/abort_controller:98:10)
    at AbortController.abort (node:internal/abort_controller:123:5)
    at Timeout.<anonymous> (file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/lib/ipfs.js:25:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'aborted'
}
```

(AbortError is because the request is aborted after 30m)

**Comment by ribasushi** [comment]
@alanshaw just timeouts on your end it seems:
```
select s.cid_v1, s.cid_original, size_actual, 1+( select count(*) from cargo.refs where cid_v1 = s.cid_v1 ) as block_count from cargo.sources s join cargo.dags using (cid_v1) where cid_original in ( 'QmVq2q1WBMHBBbQR37BKbiw9wkJThYYzHgLucAikyGYsTf', 'Qmdvh1Xa8spstyGroksPx7A7NzUpdYtEJsjy9x4kyTM385', 'QmXpR4Ai49CeUhc2WwfvpMkeTe1jEaZFkLv1YaLdBzaY6J', 'Qmazo7s2m39dZUySaeBHeVr23WhoKJvHh5gnvwbg8xRAw9' );
                           cid_v1                            |                  cid_original                  | size_actual  | block_count 
-------------------------------------------------------------+------------------------------------------------+--------------+-------------
 bafybeihhs6tqmgaruh2zyi6obb73n5thpxt3dejveonm3ye3wetdbbfy4i | Qmdvh1Xa8spstyGroksPx7A7NzUpdYtEJsjy9x4kyTM385 |  25317601395 |       97144
 bafybeidpi4kmrp3qh34i3gjkrxbi75i3n25gvygm6t4q56l7q4fs3ucldi | QmVq2q1WBMHBBbQR37BKbiw9wkJThYYzHgLucAikyGYsTf | 143846735087 |      551790
 bafybeif4chjjpfmnw2yattauahg7vswvtsahodcfe27z7w3wtjzhddxy3a | Qmazo7s2m39dZUySaeBHeVr23WhoKJvHh5gnvwbg8xRAw9 | 136964328394 |      525376
 bafybeiem2yazrwnkco6cfzsow5v25s6nqf2rfnd24hu3qs7gccntgo7aa4 | QmXpR4Ai49CeUhc2WwfvpMkeTe1jEaZFkLv1YaLdBzaY6J | 112590106062 |      431964
```
