### ISSUE TITLE
error while using /packages/client/examples/node.js/storeCar.js

### ISSUE THREAD

**Issue by jonyg80** [ipfs-shipyard/nft.storage#217]
Following error is thrown while using "/packages/client/examples/node.js/storeCar.js" file to upload a folder containing a file of 6.3GB.

```
D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@ipld\dag-pb\cjs\src\pb-encode.js:41
    bytes.set(node.Data, i);
          ^

RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.encodeNode (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@ipld\dag-pb\cjs\src\pb-encode.js:41:11)
    at encode (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@ipld\dag-pb\cjs\src\index.js:33:19)
    at DirFlat.flush (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@vascosantos\ipfs-unixfs-importer\src\dir-flat.js:109:20)
    at flush.next (<anonymous>)
    at DirFlat.flush (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@vascosantos\ipfs-unixfs-importer\src\dir-flat.js:85:26)
    at flush.next (<anonymous>)
    at flushAndYield (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@vascosantos\ipfs-unixfs-importer\src\tree-builder.js:79:16)
    at flushAndYield.next (<anonymous>)
    at treeBuilder (D:\Developement\Projects\nft.storage\packages\client\examples\node.js\node_modules\@vascosantos\ipfs-unixfs-importer\src\tree-builder.js:115:15)
```

**Comment by alanshaw** [comment]
paging @rvagg and/or @achingbrain - can you help?

**Comment by rvagg** [comment]
Nevermind, it was as suspected, an awkward maxuint32 bug that I replicated by making a single 6.3G file inside a single directory and running it through ipfs-car: https://github.com/ipld/js-dag-pb/pull/21 - test case in there matches roughly what's being seen to trigger this bug, a very simple and small block but with an awkward number that hits an edge.

**Comment by rvagg** [comment]
`@ipld/dag-pb@2.1.1` fixes this, `@vascosantos/ipfs-unixfs-importer` uses `^2.0.2` so it should pick it up on a remove & reinstall, although @vasco-santos you may want to update your ipfs-unixfs-importer fork to grab `^2.1.1` to clear this. There's been more work pushed upstream to the ipfs-unixfs branch that you've forked from that might be worth grabbing too while you're at it.

**Comment by vasco-santos** [comment]
Thanks for the ping @rvagg , I will update it now

**Comment by vasco-santos** [comment]
`@vascosantos/ipfs-unixfs-importer@9.0.3` is shipped

@jonyg80 please update your dependencies and let us know if this does not solve the problem

**Comment by jonyg80** [comment]
@vasco-santos @vascosantos/ipfs-unixfs-importer@9.0.3 solves this problem but i think version 10 again have this bug.

**Comment by vasco-santos** [comment]
@jonyg80 did you replicate the problem with it?

New unixfs-importer should be using the latest @ipld/dag-pb per https://github.com/vasco-santos/js-ipfs-unixfs/blob/chore/release-fork/packages/ipfs-unixfs-importer/package.json#L49

**Comment by jonyg80** [comment]
I am getting same problem with 2.62 GB file now
```
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.encodeNode (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@ipld\dag-pb\cjs\src\pb-encode.js:41:11)
    at encode (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@ipld\dag-pb\cjs\src\index.js:33:19)
    at DirFlat.flush (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@vascosantos\ipfs-unixfs-importer\src\dir-flat.js:109:20)
    at flush.next (<anonymous>)
    at flushAndYield (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@vascosantos\ipfs-unixfs-importer\src\tree-builder.js:79:16)
    at flushAndYield.next (<anonymous>)
    at treeBuilder (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@vascosantos\ipfs-unixfs-importer\src\tree-builder.js:115:15)
    at async Object.importer (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\@vascosantos\ipfs-unixfs-importer\src\index.js:59:20)
    at async Object.last [as default] (C:\Users\dell\AppData\Roaming\npm\node_modules\ipfs-car\node_modules\it-last\index.js:13:20)
```

**Comment by jonyg80** [comment]
```
ipfs-car --version
0.4.2
```

**Comment by vasco-santos** [comment]
can you confirm that `ipld/dag-pb` being used is `2.1.2` and that this was not happening with `@vascosantos/ipfs-unixfs-importer@9.0.3` ?

**Comment by jonyg80** [comment]
this problem is happening only with a file of (approx. 2.6 GB) , with bigger or smaller files this is working fine.
Like I tried it with 662mb file and 6.3 GB file it works fine.

**Comment by jonyg80** [comment]
Yes, `ipld/dag-pb` being used is `2.1.2` and its also happening with `@vascosantos/ipfs-unixfs-importer@9.0.3` , problem is happening as mentioned above.

**Comment by vasco-santos** [comment]
@rvagg can you help here?

**Comment by jonyg80** [comment]
https://github.com/jonyg80/js-dag-pb/runs/2987546318?check_suite_focus=true
Test results on different size ran by me.

**Comment by rvagg** [comment]
Well, this is a little embarrassing, but here's the fix, and I've pulled in your test cases too @jonyg80: https://github.com/ipld/js-dag-pb/pull/23

**Comment by mehulagg** [comment]
Fixed

**Comment by jonyg80** [comment]
Fixed
