### ISSUE TITLE
Experiencing a weird bug - unable to build on next.js

### ISSUE THREAD

**Issue by jsmellz** [ipfs-shipyard/nft.storage#458]
This error is sometimes occurring in dev mode but always on builds -

> Build error occurred
/Users/jasonsmellz/Documents/screensaver-interface/node_modules/@web-std/fetch/dist/index.cjs:1534
                        response_?.emit("error", err);
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jasonsmellz/Documents/screensaver-interface/node_modules/nft.storage/dist/src/token.cjs:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  type: 'SyntaxError'
}

**Comment by dchoi27** [comment]
@vasco-santos mind taking a quick look?
